=begin
#Railway

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ApiTransactionsReceiptsGetFieldsTransactionReceiptsParameter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ApiTransactionsReceiptsGetFieldsTransactionReceiptsParameter do
  let(:instance) { OpenapiClient::ApiTransactionsReceiptsGetFieldsTransactionReceiptsParameter.new }

  describe 'test an instance of ApiTransactionsReceiptsGetFieldsTransactionReceiptsParameter' do
    it 'should create an instance of ApiTransactionsReceiptsGetFieldsTransactionReceiptsParameter' do
      expect(instance).to be_instance_of(OpenapiClient::ApiTransactionsReceiptsGetFieldsTransactionReceiptsParameter)
    end
  end
end
