/*
 * Railway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AnyOfstring;
import org.openapitools.client.model.AnyOfstringstring;
import org.openapitools.client.model.AnyOfstringstringstring;
import org.openapitools.client.model.AnyOfstringstringstringstring;
import org.openapitools.client.model.AnyOfstringstringstringstringstring;
import org.openapitools.client.model.AnyOfstringstringstringstringstringstring;
import org.openapitools.client.model.AnyOfstringstringstringstringstringstringstringstring;
import org.openapitools.client.model.AnyOfstringstringstringstringstringstringstringstringstring;
import org.openapitools.client.model.AnyOfstringstringstringstringstringstringstringstringstringstring;
import org.openapitools.client.model.ApiAccountsGet200Response;
import org.openapitools.client.model.ApiAccountsMetadataGet200Response;
import org.openapitools.client.model.ApiBlocksGet200Response;
import org.openapitools.client.model.ApiEntitiesGet200Response;
import org.openapitools.client.model.ApiTransactionsGet200Response;
import org.openapitools.client.model.ApiTransactionsMetadataGet200Response;
import org.openapitools.client.model.ApiTransactionsReceiptsGet200Response;
import org.openapitools.client.model.ApiValidatorsUpdatesGet200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * List accounts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiAccountsGetTest() throws ApiException {
        ApiAccountsGetFieldsAccountsParameter fieldsAccounts = null;
        String filterAddress = null;
        String filterAddressNeq = null;
        String filterAddressLike = null;
        String filterAddressIlike = null;
        String filterPublicKey = null;
        String filterPublicKeyNeq = null;
        String filterPublicKeyLike = null;
        String filterPublicKeyIlike = null;
        String filterName = null;
        String filterNameNeq = null;
        String filterNameLike = null;
        String filterNameIlike = null;
        Integer filterNonce = null;
        String filterValidatorAddress = null;
        String filterValidatorAddressNeq = null;
        String filterValidatorAddressLike = null;
        String filterValidatorAddressIlike = null;
        String filterValidatorPublicKey = null;
        String filterValidatorPublicKeyNeq = null;
        String filterValidatorPublicKeyLike = null;
        String filterValidatorPublicKeyIlike = null;
        String filterValidatorPower = null;
        String filterValidatorPowerNeq = null;
        String filterValidatorPowerLike = null;
        String filterValidatorPowerIlike = null;
        ApiAccountsGetIncludeParameter include = null;
        ApiAccountsGetSortParameter sort = null;
        ApiAccountsGet200Response response = api.apiAccountsGet(fieldsAccounts, filterAddress, filterAddressNeq, filterAddressLike, filterAddressIlike, filterPublicKey, filterPublicKeyNeq, filterPublicKeyLike, filterPublicKeyIlike, filterName, filterNameNeq, filterNameLike, filterNameIlike, filterNonce, filterValidatorAddress, filterValidatorAddressNeq, filterValidatorAddressLike, filterValidatorAddressIlike, filterValidatorPublicKey, filterValidatorPublicKeyNeq, filterValidatorPublicKeyLike, filterValidatorPublicKeyIlike, filterValidatorPower, filterValidatorPowerNeq, filterValidatorPowerLike, filterValidatorPowerIlike, include, sort);
        // TODO: test validations
    }

    /**
     * List account metadata
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiAccountsMetadataGetTest() throws ApiException {
        ApiAccountsMetadataGetFieldsAccountsMetadataParameter fieldsAccountsMetadata = null;
        Integer filterAccountId = null;
        String filterModule = null;
        String filterModuleNeq = null;
        String filterModuleLike = null;
        String filterModuleIlike = null;
        String filterKey = null;
        String filterKeyNeq = null;
        String filterKeyLike = null;
        String filterKeyIlike = null;
        String filterValue = null;
        String filterValueNeq = null;
        String filterValueLike = null;
        String filterValueIlike = null;
        ApiAccountsMetadataGetIncludeParameter include = null;
        ApiAccountsMetadataGetSortParameter sort = null;
        ApiAccountsMetadataGet200Response response = api.apiAccountsMetadataGet(fieldsAccountsMetadata, filterAccountId, filterModule, filterModuleNeq, filterModuleLike, filterModuleIlike, filterKey, filterKeyNeq, filterKeyLike, filterKeyIlike, filterValue, filterValueNeq, filterValueLike, filterValueIlike, include, sort);
        // TODO: test validations
    }

    /**
     * List blocks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiBlocksGetTest() throws ApiException {
        ApiBlocksGetFieldsBlocksParameter fieldsBlocks = null;
        String filterHash = null;
        String filterHashNeq = null;
        String filterHashLike = null;
        String filterHashIlike = null;
        Integer filterHeight = null;
        Integer filterHeaderVersionBlock = null;
        String filterHeaderChainId = null;
        String filterHeaderChainIdNeq = null;
        String filterHeaderChainIdLike = null;
        String filterHeaderChainIdIlike = null;
        Integer filterHeaderHeight = null;
        String filterHeaderTime = null;
        String filterHeaderTimeNeq = null;
        String filterHeaderTimeLike = null;
        String filterHeaderTimeIlike = null;
        String filterHeaderLastBlockIdHash = null;
        String filterHeaderLastBlockIdHashNeq = null;
        String filterHeaderLastBlockIdHashLike = null;
        String filterHeaderLastBlockIdHashIlike = null;
        Integer filterHeaderLastBlockIdPartSetHeaderTotal = null;
        String filterHeaderLastBlockIdPartSetHeaderHash = null;
        String filterHeaderLastBlockIdPartSetHeaderHashNeq = null;
        String filterHeaderLastBlockIdPartSetHeaderHashLike = null;
        String filterHeaderLastBlockIdPartSetHeaderHashIlike = null;
        String filterHeaderLastCommitHash = null;
        String filterHeaderLastCommitHashNeq = null;
        String filterHeaderLastCommitHashLike = null;
        String filterHeaderLastCommitHashIlike = null;
        String filterHeaderDataHash = null;
        String filterHeaderDataHashNeq = null;
        String filterHeaderDataHashLike = null;
        String filterHeaderDataHashIlike = null;
        String filterHeaderValidatorsHash = null;
        String filterHeaderValidatorsHashNeq = null;
        String filterHeaderValidatorsHashLike = null;
        String filterHeaderValidatorsHashIlike = null;
        String filterHeaderNextValidatorsHash = null;
        String filterHeaderNextValidatorsHashNeq = null;
        String filterHeaderNextValidatorsHashLike = null;
        String filterHeaderNextValidatorsHashIlike = null;
        String filterHeaderConsensusHash = null;
        String filterHeaderConsensusHashNeq = null;
        String filterHeaderConsensusHashLike = null;
        String filterHeaderConsensusHashIlike = null;
        String filterHeaderAppHash = null;
        String filterHeaderAppHashNeq = null;
        String filterHeaderAppHashLike = null;
        String filterHeaderAppHashIlike = null;
        String filterHeaderLastResultsHash = null;
        String filterHeaderLastResultsHashNeq = null;
        String filterHeaderLastResultsHashLike = null;
        String filterHeaderLastResultsHashIlike = null;
        String filterHeaderEvidenceHash = null;
        String filterHeaderEvidenceHashNeq = null;
        String filterHeaderEvidenceHashLike = null;
        String filterHeaderEvidenceHashIlike = null;
        String filterHeaderProposerAddress = null;
        String filterHeaderProposerAddressNeq = null;
        String filterHeaderProposerAddressLike = null;
        String filterHeaderProposerAddressIlike = null;
        ApiBlocksGetIncludeParameter include = null;
        ApiBlocksGetSortParameter sort = null;
        ApiBlocksGet200Response response = api.apiBlocksGet(fieldsBlocks, filterHash, filterHashNeq, filterHashLike, filterHashIlike, filterHeight, filterHeaderVersionBlock, filterHeaderChainId, filterHeaderChainIdNeq, filterHeaderChainIdLike, filterHeaderChainIdIlike, filterHeaderHeight, filterHeaderTime, filterHeaderTimeNeq, filterHeaderTimeLike, filterHeaderTimeIlike, filterHeaderLastBlockIdHash, filterHeaderLastBlockIdHashNeq, filterHeaderLastBlockIdHashLike, filterHeaderLastBlockIdHashIlike, filterHeaderLastBlockIdPartSetHeaderTotal, filterHeaderLastBlockIdPartSetHeaderHash, filterHeaderLastBlockIdPartSetHeaderHashNeq, filterHeaderLastBlockIdPartSetHeaderHashLike, filterHeaderLastBlockIdPartSetHeaderHashIlike, filterHeaderLastCommitHash, filterHeaderLastCommitHashNeq, filterHeaderLastCommitHashLike, filterHeaderLastCommitHashIlike, filterHeaderDataHash, filterHeaderDataHashNeq, filterHeaderDataHashLike, filterHeaderDataHashIlike, filterHeaderValidatorsHash, filterHeaderValidatorsHashNeq, filterHeaderValidatorsHashLike, filterHeaderValidatorsHashIlike, filterHeaderNextValidatorsHash, filterHeaderNextValidatorsHashNeq, filterHeaderNextValidatorsHashLike, filterHeaderNextValidatorsHashIlike, filterHeaderConsensusHash, filterHeaderConsensusHashNeq, filterHeaderConsensusHashLike, filterHeaderConsensusHashIlike, filterHeaderAppHash, filterHeaderAppHashNeq, filterHeaderAppHashLike, filterHeaderAppHashIlike, filterHeaderLastResultsHash, filterHeaderLastResultsHashNeq, filterHeaderLastResultsHashLike, filterHeaderLastResultsHashIlike, filterHeaderEvidenceHash, filterHeaderEvidenceHashNeq, filterHeaderEvidenceHashLike, filterHeaderEvidenceHashIlike, filterHeaderProposerAddress, filterHeaderProposerAddressNeq, filterHeaderProposerAddressLike, filterHeaderProposerAddressIlike, include, sort);
        // TODO: test validations
    }

    /**
     * List entities
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiEntitiesGetTest() throws ApiException {
        ApiEntitiesGetFieldsEntitiesParameter fieldsEntities = null;
        String filterModule = null;
        String filterModuleNeq = null;
        String filterModuleLike = null;
        String filterModuleIlike = null;
        String filterType = null;
        String filterTypeNeq = null;
        String filterTypeLike = null;
        String filterTypeIlike = null;
        String filterKey = null;
        String filterKeyNeq = null;
        String filterKeyLike = null;
        String filterKeyIlike = null;
        String filterValue = null;
        String filterValueNeq = null;
        String filterValueLike = null;
        String filterValueIlike = null;
        ApiEntitiesGetSortParameter sort = null;
        ApiEntitiesGet200Response response = api.apiEntitiesGet(fieldsEntities, filterModule, filterModuleNeq, filterModuleLike, filterModuleIlike, filterType, filterTypeNeq, filterTypeLike, filterTypeIlike, filterKey, filterKeyNeq, filterKeyLike, filterKeyIlike, filterValue, filterValueNeq, filterValueLike, filterValueIlike, sort);
        // TODO: test validations
    }

    /**
     * List transactions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiTransactionsGetTest() throws ApiException {
        ApiTransactionsGetFieldsAccountsParameter fieldsAccounts = null;
        String filterHash = null;
        String filterHashNeq = null;
        String filterHashLike = null;
        String filterHashIlike = null;
        String filterSender = null;
        String filterSenderNeq = null;
        String filterSenderLike = null;
        String filterSenderIlike = null;
        String filterRecipient = null;
        String filterRecipientNeq = null;
        String filterRecipientLike = null;
        String filterRecipientIlike = null;
        Integer filterGas = null;
        Integer filterNonce = null;
        String filterSignature = null;
        String filterSignatureNeq = null;
        String filterSignatureLike = null;
        String filterSignatureIlike = null;
        String filterVersion = null;
        String filterVersionNeq = null;
        String filterVersionLike = null;
        String filterVersionIlike = null;
        String filterMessageHandler = null;
        String filterMessageHandlerNeq = null;
        String filterMessageHandlerLike = null;
        String filterMessageHandlerIlike = null;
        String filterMessageVersion = null;
        String filterMessageVersionNeq = null;
        String filterMessageVersionLike = null;
        String filterMessageVersionIlike = null;
        String filterMessageNetwork = null;
        String filterMessageNetworkNeq = null;
        String filterMessageNetworkLike = null;
        String filterMessageNetworkIlike = null;
        String filterMessageContent = null;
        String filterMessageContentNeq = null;
        String filterMessageContentLike = null;
        String filterMessageContentIlike = null;
        ApiTransactionsGetIncludeParameter include = null;
        ApiTransactionsGetSortParameter sort = null;
        ApiTransactionsGet200Response response = api.apiTransactionsGet(fieldsAccounts, filterHash, filterHashNeq, filterHashLike, filterHashIlike, filterSender, filterSenderNeq, filterSenderLike, filterSenderIlike, filterRecipient, filterRecipientNeq, filterRecipientLike, filterRecipientIlike, filterGas, filterNonce, filterSignature, filterSignatureNeq, filterSignatureLike, filterSignatureIlike, filterVersion, filterVersionNeq, filterVersionLike, filterVersionIlike, filterMessageHandler, filterMessageHandlerNeq, filterMessageHandlerLike, filterMessageHandlerIlike, filterMessageVersion, filterMessageVersionNeq, filterMessageVersionLike, filterMessageVersionIlike, filterMessageNetwork, filterMessageNetworkNeq, filterMessageNetworkLike, filterMessageNetworkIlike, filterMessageContent, filterMessageContentNeq, filterMessageContentLike, filterMessageContentIlike, include, sort);
        // TODO: test validations
    }

    /**
     * List transaction metadata
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiTransactionsMetadataGetTest() throws ApiException {
        ApiTransactionsMetadataGetFieldsTransactionMetadataParameter fieldsTransactionMetadata = null;
        Integer filterTransactionId = null;
        String filterKey = null;
        String filterKeyNeq = null;
        String filterKeyLike = null;
        String filterKeyIlike = null;
        String filterValue = null;
        String filterValueNeq = null;
        String filterValueLike = null;
        String filterValueIlike = null;
        ApiTransactionsMetadataGetIncludeParameter include = null;
        ApiTransactionsMetadataGetSortParameter sort = null;
        ApiTransactionsMetadataGet200Response response = api.apiTransactionsMetadataGet(fieldsTransactionMetadata, filterTransactionId, filterKey, filterKeyNeq, filterKeyLike, filterKeyIlike, filterValue, filterValueNeq, filterValueLike, filterValueIlike, include, sort);
        // TODO: test validations
    }

    /**
     * List transaction receipts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiTransactionsReceiptsGetTest() throws ApiException {
        ApiTransactionsReceiptsGetFieldsTransactionReceiptsParameter fieldsTransactionReceipts = null;
        Integer filterTransactionId = null;
        String filterBlockHash = null;
        String filterBlockHashNeq = null;
        String filterBlockHashLike = null;
        String filterBlockHashIlike = null;
        String filterBlockNumber = null;
        String filterBlockNumberNeq = null;
        String filterBlockNumberLike = null;
        String filterBlockNumberIlike = null;
        ApiTransactionsMetadataGetIncludeParameter include = null;
        ApiTransactionsReceiptsGetSortParameter sort = null;
        ApiTransactionsReceiptsGet200Response response = api.apiTransactionsReceiptsGet(fieldsTransactionReceipts, filterTransactionId, filterBlockHash, filterBlockHashNeq, filterBlockHashLike, filterBlockHashIlike, filterBlockNumber, filterBlockNumberNeq, filterBlockNumberLike, filterBlockNumberIlike, include, sort);
        // TODO: test validations
    }

    /**
     * List validator updates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiValidatorsUpdatesGetTest() throws ApiException {
        ApiValidatorsUpdatesGetFieldsBlockNumberParameter fieldsBlockNumber = null;
        Integer filterBlockNumber = null;
        ApiValidatorsUpdatesGetIncludeParameter include = null;
        ApiValidatorsUpdatesGetSortParameter sort = null;
        ApiValidatorsUpdatesGet200Response response = api.apiValidatorsUpdatesGet(fieldsBlockNumber, filterBlockNumber, include, sort);
        // TODO: test validations
    }

}
