=begin
#Railway

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/account'
require 'openapi_client/models/account_metadata'
require 'openapi_client/models/api_accounts_get200_response'
require 'openapi_client/models/api_accounts_get_fields_accounts_parameter'
require 'openapi_client/models/api_accounts_get_include_parameter'
require 'openapi_client/models/api_accounts_get_sort_parameter'
require 'openapi_client/models/api_accounts_metadata_get200_response'
require 'openapi_client/models/api_accounts_metadata_get_fields_accounts_metadata_parameter'
require 'openapi_client/models/api_accounts_metadata_get_include_parameter'
require 'openapi_client/models/api_accounts_metadata_get_sort_parameter'
require 'openapi_client/models/api_blocks_get200_response'
require 'openapi_client/models/api_blocks_get_fields_blocks_parameter'
require 'openapi_client/models/api_blocks_get_include_parameter'
require 'openapi_client/models/api_blocks_get_sort_parameter'
require 'openapi_client/models/api_entities_get200_response'
require 'openapi_client/models/api_entities_get_fields_entities_parameter'
require 'openapi_client/models/api_entities_get_sort_parameter'
require 'openapi_client/models/api_transactions_get200_response'
require 'openapi_client/models/api_transactions_get_fields_accounts_parameter'
require 'openapi_client/models/api_transactions_get_include_parameter'
require 'openapi_client/models/api_transactions_get_sort_parameter'
require 'openapi_client/models/api_transactions_metadata_get200_response'
require 'openapi_client/models/api_transactions_metadata_get_fields_transaction_metadata_parameter'
require 'openapi_client/models/api_transactions_metadata_get_include_parameter'
require 'openapi_client/models/api_transactions_metadata_get_sort_parameter'
require 'openapi_client/models/api_transactions_receipts_get200_response'
require 'openapi_client/models/api_transactions_receipts_get_fields_transaction_receipts_parameter'
require 'openapi_client/models/api_transactions_receipts_get_sort_parameter'
require 'openapi_client/models/api_validators_updates_get200_response'
require 'openapi_client/models/api_validators_updates_get_fields_block_number_parameter'
require 'openapi_client/models/api_validators_updates_get_include_parameter'
require 'openapi_client/models/api_validators_updates_get_sort_parameter'
require 'openapi_client/models/block'
require 'openapi_client/models/entity'
require 'openapi_client/models/transaction'
require 'openapi_client/models/transaction_metadata'
require 'openapi_client/models/transaction_receipt'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
