/**
 * Railway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The id of the object.
 * @param accountId The id of the object.
 * @param module The id of the object.
 * @param key The id of the object.
 * @param `value` The id of the object.
 * @param createdAt The creation date of the object.
 * @param updatedAt The updating date of the object.
 */

data class AccountMetadata (

    /* The id of the object. */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The id of the object. */
    @Json(name = "account_id")
    val accountId: kotlin.Int? = null,

    /* The id of the object. */
    @Json(name = "module")
    val module: kotlin.String? = null,

    /* The id of the object. */
    @Json(name = "key")
    val key: kotlin.String? = null,

    /* The id of the object. */
    @Json(name = "value")
    val `value`: kotlin.String? = null,

    /* The creation date of the object. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    /* The updating date of the object. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null

)

