/**
 * Railway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The id of the object.
 * @param hash The hash of the object.
 * @param height The height of the object.
 * @param header The id of the object.
 * @param byzantineValidators The id of the object.
 * @param lastCommitInfo The id of the object.
 * @param createdAt The creation date of the object.
 * @param updatedAt The updating date of the object.
 */

data class Block (

    /* The id of the object. */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The hash of the object. */
    @Json(name = "hash")
    val hash: kotlin.String? = null,

    /* The height of the object. */
    @Json(name = "height")
    val height: kotlin.Int? = null,

    /* The id of the object. */
    @Json(name = "header")
    val header: kotlin.collections.List? = null,

    /* The id of the object. */
    @Json(name = "byzantine_validators")
    val byzantineValidators: kotlin.collections.List? = null,

    /* The id of the object. */
    @Json(name = "last_commit_info")
    val lastCommitInfo: kotlin.collections.List? = null,

    /* The creation date of the object. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    /* The updating date of the object. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null

)

