/**
 * Railway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The internal id of the object.
 * @param blockId The id of the block associated with the object.
 * @param hash The unique hash of the object.
 * @param sender The public key of the recipient associated with the object.
 * @param recipient The address of the recipient associated with the object.
 * @param gas The amount of gas of the object.
 * @param nonce The nonce of the account associated with the object.
 * @param signature The signature of the object.
 * @param version The version of the object.
 * @param message The message of the object.
 * @param messageDeserialized The deserialized message of the object.
 * @param createdAt The creation date of the object.
 * @param updatedAt The updating date of the object.
 */

data class Transaction (

    /* The internal id of the object. */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The id of the block associated with the object. */
    @Json(name = "block_id")
    val blockId: kotlin.Int? = null,

    /* The unique hash of the object. */
    @Json(name = "hash")
    val hash: kotlin.String? = null,

    /* The public key of the recipient associated with the object. */
    @Json(name = "sender")
    val sender: kotlin.String? = null,

    /* The address of the recipient associated with the object. */
    @Json(name = "recipient")
    val recipient: kotlin.String? = null,

    /* The amount of gas of the object. */
    @Json(name = "gas")
    val gas: kotlin.Int? = null,

    /* The nonce of the account associated with the object. */
    @Json(name = "nonce")
    val nonce: kotlin.Int? = null,

    /* The signature of the object. */
    @Json(name = "signature")
    val signature: kotlin.String? = null,

    /* The version of the object. */
    @Json(name = "version")
    val version: kotlin.String? = null,

    /* The message of the object. */
    @Json(name = "message")
    val message: kotlin.collections.List? = null,

    /* The deserialized message of the object. */
    @Json(name = "message_deserialized")
    val messageDeserialized: kotlin.collections.List? = null,

    /* The creation date of the object. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    /* The updating date of the object. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null

)

