/*
 * Railway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Account {
    /// The internal id of the object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The id of the object.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// The id of the object.
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    /// The id of the object.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The id of the object.
    #[serde(rename = "nonce", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<i32>,
    /// The id of the object.
    #[serde(rename = "balances", skip_serializing_if = "Option::is_none")]
    pub balances: Option<String>,
    /// The id of the object.
    #[serde(rename = "locked_balances", skip_serializing_if = "Option::is_none")]
    pub locked_balances: Option<String>,
    /// The id of the object.
    #[serde(rename = "stakes", skip_serializing_if = "Option::is_none")]
    pub stakes: Option<String>,
    /// The id of the object.
    #[serde(rename = "validator", skip_serializing_if = "Option::is_none")]
    pub validator: Option<String>,
    /// The id of the object.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    /// The creation date of the object.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The updating date of the object.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl Account {
    pub fn new() -> Account {
        Account {
            id: None,
            address: None,
            public_key: None,
            name: None,
            nonce: None,
            balances: None,
            locked_balances: None,
            stakes: None,
            validator: None,
            metadata: None,
            created_at: None,
            updated_at: None,
        }
    }
}


