/*
 * Railway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Block {
    /// The id of the object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The hash of the object.
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// The height of the object.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    /// The id of the object.
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<crate::models::Array>,
    /// The id of the object.
    #[serde(rename = "byzantine_validators", skip_serializing_if = "Option::is_none")]
    pub byzantine_validators: Option<crate::models::Array>,
    /// The id of the object.
    #[serde(rename = "last_commit_info", skip_serializing_if = "Option::is_none")]
    pub last_commit_info: Option<crate::models::Array>,
    /// The creation date of the object.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The updating date of the object.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl Block {
    pub fn new() -> Block {
        Block {
            id: None,
            hash: None,
            height: None,
            header: None,
            byzantine_validators: None,
            last_commit_info: None,
            created_at: None,
            updated_at: None,
        }
    }
}


