/*
 * Railway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionReceipt {
    /// The id of the object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The id of the object.
    #[serde(rename = "transaction_id", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<i32>,
    /// The id of the object.
    #[serde(rename = "block_hash", skip_serializing_if = "Option::is_none")]
    pub block_hash: Option<String>,
    /// The id of the object.
    #[serde(rename = "block_number", skip_serializing_if = "Option::is_none")]
    pub block_number: Option<i32>,
    /// The id of the object.
    #[serde(rename = "logs", skip_serializing_if = "Option::is_none")]
    pub logs: Option<crate::models::Array>,
    /// The creation date of the object.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The updating date of the object.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl TransactionReceipt {
    pub fn new() -> TransactionReceipt {
        TransactionReceipt {
            id: None,
            transaction_id: None,
            block_hash: None,
            block_number: None,
            logs: None,
            created_at: None,
            updated_at: None,
        }
    }
}


