/*
Railway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiAccountsMetadataGet200Response struct for ApiAccountsMetadataGet200Response
type ApiAccountsMetadataGet200Response struct {
	Data *Array `json:"data,omitempty"`
	Links map[string]interface{} `json:"links,omitempty"`
	Meta map[string]interface{} `json:"meta,omitempty"`
}

// NewApiAccountsMetadataGet200Response instantiates a new ApiAccountsMetadataGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAccountsMetadataGet200Response() *ApiAccountsMetadataGet200Response {
	this := ApiAccountsMetadataGet200Response{}
	return &this
}

// NewApiAccountsMetadataGet200ResponseWithDefaults instantiates a new ApiAccountsMetadataGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAccountsMetadataGet200ResponseWithDefaults() *ApiAccountsMetadataGet200Response {
	this := ApiAccountsMetadataGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiAccountsMetadataGet200Response) GetData() Array {
	if o == nil || o.Data == nil {
		var ret Array
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsMetadataGet200Response) GetDataOk() (*Array, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiAccountsMetadataGet200Response) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given Array and assigns it to the Data field.
func (o *ApiAccountsMetadataGet200Response) SetData(v Array) {
	o.Data = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ApiAccountsMetadataGet200Response) GetLinks() map[string]interface{} {
	if o == nil || o.Links == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsMetadataGet200Response) GetLinksOk() (map[string]interface{}, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ApiAccountsMetadataGet200Response) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]interface{} and assigns it to the Links field.
func (o *ApiAccountsMetadataGet200Response) SetLinks(v map[string]interface{}) {
	o.Links = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ApiAccountsMetadataGet200Response) GetMeta() map[string]interface{} {
	if o == nil || o.Meta == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsMetadataGet200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ApiAccountsMetadataGet200Response) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *ApiAccountsMetadataGet200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o ApiAccountsMetadataGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableApiAccountsMetadataGet200Response struct {
	value *ApiAccountsMetadataGet200Response
	isSet bool
}

func (v NullableApiAccountsMetadataGet200Response) Get() *ApiAccountsMetadataGet200Response {
	return v.value
}

func (v *NullableApiAccountsMetadataGet200Response) Set(val *ApiAccountsMetadataGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAccountsMetadataGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAccountsMetadataGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAccountsMetadataGet200Response(val *ApiAccountsMetadataGet200Response) *NullableApiAccountsMetadataGet200Response {
	return &NullableApiAccountsMetadataGet200Response{value: val, isSet: true}
}

func (v NullableApiAccountsMetadataGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAccountsMetadataGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


