/*
 * Railway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApiEntitiesGetSortParameter
 */
public class ApiEntitiesGetSortParameterTest {
    private final ApiEntitiesGetSortParameter model = new ApiEntitiesGetSortParameter();

    /**
     * Model tests for ApiEntitiesGetSortParameter
     */
    @Test
    public void testApiEntitiesGetSortParameter() {
        // TODO: test ApiEntitiesGetSortParameter
    }

}
